### ISSUE TITLE
Boolean is serialized to a string

### ISSUE THREAD

**Issue by PegWeb** [kevindb/cf-mailchimp#3]
We need the ability to add a subscriber directly to a group/interest in our mailing list. So for example our master list has 3 groups in it. We have figured out how to get the group/interest ID and we tried to modify the code like so.

`<cfscript>
mc = new cfc.mailchimp(
	apiKey = "MYAPIKEYHERE",  // see http://kb.mailchimp.com/accounts/management/about-api-keys
	serviceURL = "https://us1.api.mailchimp.com/3.0/",
	debug = false            // note debug setting
);

lists = mc.getLists();

newMember = mc.putListMember(
	listId = "MainListID",  // see http://kb.mailchimp.com/lists/managing-subscribers/find-your-list-id
	data = {
		"email_address" = "#FORM.EMAIL#",
		"status" = "subscribed",
		"merge_fields" = {
			"FNAME" = "#FORM.FNAME#",
			"LNAME" = "#FORM.LNAME#"
		},
		"interests"  = {"GroupID" = true}
	}
);
</cfscript>`

When we attempt this we get this back.

_Schema describes boolean, string found instead_

Any idea how this could be accomplished?

**Comment by kevindb** [comment]
What version of ColdFusion or Lucee are you using? What version of cf-mailchimp are you using?

**Comment by PegWeb** [comment]
CF 11 (2016) and cf-mailchimp 1.1

**Comment by kevindb** [comment]
This sounds like the Adobe ColdFusion JSON serializer is silently changing your variable types.
Do you have `JSONUtil.cfc` in the same folder as `mailchimp.cfc`? ([documentation](https://github.com/kevindb/cf-mailchimp#jsonutil-dependency))
If so, please set `debug = true` in your init and post the debugging results here.

**Comment by PegWeb** [comment]
![mail chimp tester](https://cloud.githubusercontent.com/assets/1828969/25031657/7afe34a2-209c-11e7-8067-c7b94654babe.png)

**Comment by kevindb** [comment]
I believe I've fixed the issue in [version 1.1.1](https://github.com/kevindb/cf-mailchimp/releases/tag/v1.1.1). Please download the latest version of mailchimp.cfc and make sure you still have JSONUtil.cfc in the same folder. Let me know how it goes!

**Comment by PegWeb** [comment]
Looks like it is still throwing an error. :(
![image](https://cloud.githubusercontent.com/assets/1828969/25101956/4bde488e-2384-11e7-8044-c197522be612.png)

**Comment by kevindb** [comment]
What is the error you're getting back from MailChimp?

**Comment by PegWeb** [comment]
400 bad request according to the debug content

**Comment by kevindb** [comment]
At this point, you'll need to contact MailChimp support to find out what is wrong. "Bad request" does not contain any useful information to indicate what is bad about the request.

**Comment by PegWeb** [comment]
Ok I'll play with it and let you know if I find out anything additional.

**Comment by PegWeb** [comment]
So I did a dump of what was returned and got a little more information.

_Invalid interest ID: 'GroupID'._

I found a comment that shows how to obtain that ID so I did and I switched it out.

http://stackoverflow.com/questions/37311116/can-you-get-a-mailchimp-interest-group-id-without-using-the-api#

But now they are returning a 404 error which is weird.

**Comment by kevindb** [comment]
I suggest you open a support ticket with MailChimp. They can monitor your API requests and give you far more information about what is wrong.

**Comment by PegWeb** [comment]
Ok I might have an idea of the issue here. With debug turned on at the top I see the following for the PUT.

HTTP PUT: https://us14.api.mailchimp.com/3.0/lists/b502807fa1/members/9c3e346a14c35d7dc731f194ed748d81?EXCLUDE_FIELDS=%5Flinks

However when I am in the MailChimp playground and I drill down to the interest in my list I see the following GET at the top.

GET lists/2a59fc5db3/interest-categories/b502807fa1/interests/f93091a542

So is the reason I am getting a 404 is because the code is doing a PUT to the wrong place and it should look more like this?

https://us14.api.mailchimp.com/3.0/lists/b502807fa1//interests/f93091a542

Just speculating.

**Comment by PegWeb** [comment]
Got this back from MailChimp support.

May 17, 12:57 AM EDT 
Hey there

Thanks for reaching out to MailChimp API Support. I would happy to assist with building this particular call. 

With adding a contact to a group through the API, this is done through the /lists/{List_id}/members endpoint. Interest is an object in which the interest id and a boolean is used. This format can be seen in the example response in our developer reference: http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#

**Comment by PegWeb** [comment]
I finally figured this out. I was leaving the word GroupID in this line
"interests" = {"GroupID" = true}
instead of actually using the group ID there. I was using the GroupID in place of the MainListID because I misunderstood how I thought it worked.

**Comment by kevindb** [comment]
So, instead of `"interests" = {"GroupID" = true}`, you're doing something like
`"interests" = {98486 = true}` ?

**Comment by PegWeb** [comment]
I am now yes and that is working. I orginally thought the GroupID = true was just some sort of flag indicating to their API that the listID being passed was the groupID.

**Comment by kevindb** [comment]
Excellent! I'm glad you got it working!
